name: Check

concurrency:
  group: ${{ github.workflow }}.${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_call:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/base

      - run: pnpm markdownlint --ignore-path .gitignore ./**/*.md

      - run: pnpm oxfmt --check --no-error-on-unmatched-pattern .

      - run: pnpm oxlint --type-aware

      - run: pnpm knip --cache --cache-location .knipcache

      - run: pnpm cspell lint --no-progress --gitignore --show-context --cache ./**/*

      - run: pnpm type-check

      - run: pnpm test
        env:
          V2_API_KEY: ${{ secrets.V2_API_KEY }}
          V2_API_KEY_SECRET: ${{ secrets.V2_API_KEY_SECRET }}
          V2_API_KEY_PASSPHRASE: ${{ secrets.V2_API_KEY_PASSPHRASE }}
          V3_API_KEY: ${{ secrets.V3_API_KEY }}
          V3_API_KEY_SECRET: ${{ secrets.V3_API_KEY_SECRET }}
          V3_API_KEY_PASSPHRASE: ${{ secrets.V3_API_KEY_PASSPHRASE }}
