name: Check

concurrency:
  group: ${{ github.workflow }}.${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_call:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/base

      - run: pnpm markdownlint --ignore-path .gitignore ./**/*.md

      - run: pnpm prettier --check --no-error-on-unmatched-pattern --cache --cache-location .prettiercache .

      - run: pnpm oxlint --type-aware

      - run: pnpm knip --cache --cache-location .knipcache

      - run: pnpm cspell lint --no-progress --gitignore --show-context --cache ./**/*

      - run: pnpm type-check

      - run: pnpm test
        env:
          LNM_API_NETWORK: testnet
          LNM_API_KEY: ${{ secrets.LNM_API_KEY }}
          LNM_API_SECRET: ${{ secrets.LNM_API_SECRET }}
          LNM_API_PASSPHRASE: ${{ secrets.LNM_API_PASSPHRASE }}
